/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.InputMismatchException;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        System.out.println("=== Welcome to the Calculator App ===");
        
        try(Scanner sc = new Scanner(System.in);){
            int num1 = readInt(sc, "Enter the first number: ");
            int num2 = readInt(sc, "Enter the second number: ");

            StandardCalculator calc = new StandardCalculator(num1, num2);
            StandardCalculator.printVersion();

            performOperations(calc, num1, num2);

            sc.close();
        } catch(ArithmeticException e){
            System.err.println("Math err       : " + e.getMessage());
        } catch(Exception e){
            System.err.println("Unexpected err     : " + e.getMessage());
        }
    }

    private static int readInt(Scanner sc, String prompt){
        while(true){
            System.out.print(prompt);
            try{
                return sc.nextInt();
            } catch(InputMismatchException e){
                System.err.println("Invalid input. Please enter a whole number. ");
                sc.nextLine();
            }
        }
    }

    private static void performOperations(StandardCalculator calc, int num1, int num2){
        System.out.println("\n--- Results ---");

        calc.clearResult();

        calc.add(num1, num2);
        System.out.printf("Addition   : %d + %d = %.2f%n", num1, num2, calc.getResult());

        calc.subtract(num1, num2);
        System.out.printf("Subtraction of   : %d - %d = %.2f%n", num1, num2, calc.getResult());

        calc.multiply(num1, num2);
        System.out.printf("Multiplication of    : %d * %d = %.2f%n", num1, num2, calc.getResult());

        calc.division(num1, num2);
        System.out.printf("Division of   : %d / %d = %.2f%n", num1, num2, calc.getResult());

        System.out.println();
        calc.printResult();
    }    
    
}
